trigger:
  - main
  - release*

pr: 
  - main
  - release*
  
resources:
- repo: self

stages:
- stage: Build
  jobs:
  - job: Windows
    timeoutInMinutes: 120

    pool:
      vmImage: windows-2022

    variables:
      HLSL_SRC_DIR: '$(Build.SourcesDirectory)'
      HLSL_BLD_DIR: '$(Agent.BuildDirectory)'
      platform: x64

    strategy:
      matrix:
        VS2022_Release:
         configuration: Release
        VS2022_Debug:
         configuration: Debug

    steps:
    - checkout: self
      clean: true
      submodules: true
    - script: |
        call utils\hct\hctstart.cmd %HLSL_SRC_DIR% %HLSL_BLD_DIR%
        call utils\hct\hctbuild.cmd -$(platform) -$(configuration) -show-cmake-log -spirvtest
      displayName: 'Building'
    - script: |
        call utils\hct\hctstart.cmd %HLSL_SRC_DIR% %HLSL_BLD_DIR%
        call utils\hct\hcttest.cmd -$(configuration) noexec
      displayName: 'DXIL Tests'
    - script: |
        call utils\hct\hctstart.cmd %HLSL_SRC_DIR% %HLSL_BLD_DIR%
        call utils\hct\hcttest.cmd -$(configuration) exec-warp
      displayName: 'DXIL Execution Tests (Nuget WARP)'

  - job: Nix
    timeoutInMinutes: 120

    variables:
      macOS: macOS-latest
      linux: Ubuntu-22.04 # FIXME: #7364, DXC does not build correctly with GCC 13+

    strategy:
      matrix:
        Linux_Clang_RelWithDebInfo:
          image: ${{ variables.linux }}
          configuration: RelWithDebInfo
          CC: clang-18
          CXX: clang++-18
          CMAKE_OPTS: -DLLVM_ENABLE_WERROR=On -DLLVM_USE_SANITIZER='Address;Undefined' -DLLVM_ENABLE_LIBCXX=On -DLLVM_USE_LINKER=lld-18
          CHECK_ALL_ENV: ASAN_OPTIONS=alloc_dealloc_mismatch=0 LSAN_OPTIONS=suppressions=$BUILD_SOURCESDIRECTORY/utils/asan/x86_64-pc-linux-gnu.lsan.supp:print_suppressions=1 ASAN_SYMBOLIZER_PATH=llvm-symbolizer-18 LSAN_SYMBOLIZER_PATH=llvm-symbolizer-18
          OS: Linux
        Linux_Clang_Debug:
          image: ${{ variables.linux }}
          configuration: Debug
          CC: clang
          CXX: clang++
          CMAKE_OPTS: -DLLVM_ENABLE_WERROR=On -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_USE_LINKER=lld
        Linux_Gcc_Release:
          image: ${{ variables.linux }}
          configuration: Release
          CC: gcc-9
          CXX: g++-9
        Linux_Gcc_Debug:
          image: ${{ variables.linux }}
          configuration: Debug
          CC: gcc-9
          CXX: g++-9
          CMAKE_OPTS: -DLLVM_ENABLE_ASSERTIONS=ON
        MacOS_Clang_Release:
          image: ${{ variables.macOS }}
          configuration: Release
          CC: clang
          CXX: clang++
          CMAKE_OPTS: -DLLVM_ENABLE_WERROR=On
          OS: MacOS
        MacOS_Clang_Debug:
          image: ${{ variables.macOS }}
          configuration: Debug
          CC: clang
          CXX: clang++
          CMAKE_OPTS: -DLLVM_ENABLE_WERROR=On -DLLVM_ENABLE_ASSERTIONS=ON

    pool:
      vmImage: $(image)

    steps:
    - checkout: self
      clean: true
      submodules: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - bash: |
        sudo apt-get install ninja-build
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install libc++-18-dev
        sudo apt-get update
        sudo apt-get upgrade libc6 libc6-dbg
        dpkg -s libc6 | grep Version # Check libc6 version ## DEBUG ##
        apt list -a libc6-dbg # Check libc6 packages ## DEBUG ##
      displayName: 'Installing dependencies'
      condition: eq(variables['image'], variables['linux'])

    - bash: |
        echo "=== Environment Variables ==="
        env | grep -i 'lang\|locale'
        echo
        echo "=== locale output ==="
        locale
        echo
        echo "=== locale -a output ==="
        locale -a
        echo
        echo "=== Locales available via /usr/share/locale and /usr/lib/locale ==="
        ls -l /usr/share/locale 2>/dev/null || echo "/usr/share/locale not found"
        ls -l /usr/lib/locale 2>/dev/null || echo "/usr/lib/locale not found"
        echo
        echo "=== glibc version (if available) ==="
        ldd --version 2>/dev/null | head -n1 || echo "ldd not found"
        echo
        echo "=== macOS version (if available) ==="
        sw_vers 2>/dev/null || echo "Not macOS or sw_vers not found"
        echo
        echo "=== Try creating C.UTF-8 and C.utf8 locales in C code ==="
        cat <<EOF > test_locale.c
        #include <locale.h>
        #include <stdio.h>
        int main() {
        locale_t loc1 = newlocale(LC_CTYPE_MASK, "C.UTF-8", NULL);
        printf("newlocale(\"C.UTF-8\"): %s\\n", loc1 ? "success" : "fail");
        if (loc1) freelocale(loc1);
        locale_t loc2 = newlocale(LC_CTYPE_MASK, "C.utf8", NULL);
        printf("newlocale(\"C.utf8\"): %s\\n", loc2 ? "success" : "fail");
        if (loc2) freelocale(loc2);
        return 0;
        }
        EOF
        cc test_locale.c -o test_locale && ./test_locale || echo "C compilation failed"
        rm -f test_locale.c test_locale
        echo
        echo "=== Done ==="
      displayName: 'Testing locale settings'
      condition: eq(variables['image'], variables['macOS'])

    - bash: |
        brew update
        brew install ninja
        ulimit -Sn 1024
      displayName: 'Installing dependencies'
      condition: eq(variables['image'], variables['macOS'])
    - bash: |
        cmake -B build -G Ninja $BUILD_SOURCESDIRECTORY -DLLVM_LIT_ARGS='-v --xunit-xml-output=testresults.xunit.xml' -C $BUILD_SOURCESDIRECTORY/cmake/caches/PredefinedParams.cmake -DSPIRV_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$(configuration) -DCMAKE_C_COMPILER=$(CC) -DCMAKE_CXX_COMPILER=$(CXX) $(CMAKE_OPTS)
      displayName: 'Running Cmake'
    - bash: |
        ninja -C build test-depends
      displayName: 'Building'
    - bash: |
        ./build/bin/dxc -T ps_6_0 tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
        ./build/bin/dxc -T ps_6_0 -Fo passthru-ps.dxil tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
        ./build/bin/dxc -T ps_6_0 -Fo passthru-ps.spv tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv -spirv
        ls -ld $AGENT_BUILDDIRECTORY
        ls -ld $BUILD_SOURCESDIRECTORY
      displayName: 'Smoke tests'
    - bash: $(CHECK_ALL_ENV) ninja -C build check-all
      displayName: 'DXC tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/testresults.xunit.xml'
      condition: succeededOrFailed()

